name: Build and Push to GHCR (amd64 only)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (e.g. 1.0.0)'
        required: true
        default: 'dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Set image version
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            VERSION=$(echo "${{ github.ref }}" | sed -E 's|refs/tags/v||' || echo "latest")
            echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push (amd64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/shift-code:latest
            ghcr.io/${{ github.repository_owner }}/shift-code:${{ steps.vars.outputs.VERSION }}
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}
